[build]
  publish = "/"  
  functions = "netlify/functions"

# Form handling
[[forms]]
  name = "download-form"
  
[[forms.download-form.notifications]]
  event = "submission-created"
  url = "/.netlify/functions/form-submission"
  handler = "form-submission"
  
[context.development.environment]
  SITE_URL = "http://localhost:8888"

[context.production.environment]
  SITE_URL = "https://bogoodski-book.netlify.app"